server:
  port: 10087 # 自己的端口

spring:
  application:
    name:  eureka-server # 自己的服务的名字,注册提供的名字

eureka:
  client:
    register-with-eureka: true  # 是否进行注册
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka # 注册到哪里去


  instance:
      prefer-ip-address: true # 希望使用自己的IP地址
      ip-address: 127.0.0.1  # 希望使用自己的IP地址
      instance-id: 127.0.0.1 # 注册时使用自己的IP地址
      lease-renewal-interval-in-seconds: 30 # 维持心跳,30秒心跳一次,最小续约周期,证明自己存在
      lease-expiration-duration-in-seconds: 0 # 超过90秒没有发送,就证明挂了

  server:
    eviction-interval-timer-in-ms: 60000 # 失效剔除
    enable-self-preservation: true # 开启自我保护机制